Import('*')

target = ['#output/derived/bootstrap_census/Weaver_2021_Replicates.csv',
          '#output/derived/bootstrap_census/Weaver_2021_Estimates.csv',
          '#output/derived/bootstrap_census/Weaver_2021_Replicates.log',
          '#output/derived/bootstrap_census/Weaver_2021_Estimates.log']
source = ['#source/derived/bootstrap_census/Weaver_2021/clean_replicates.py',
          '#datastore/raw/bootstrap_census/Weaver_2021/orig/bootstrap_coefs.xlsx',
          '#source/raw/bootstrap_census/orig/objects_of_interest.csv']
env.Python(target, source)
