Import('*')

target = ['#output/derived/Finkelstein_Gentzkow_Williams_2021_Replicates.csv',
          '#output/derived/Finkelstein_Gentzkow_Williams_2021_Estimates.csv',
          '#output/derived/Finkelstein_Gentzkow_Williams_2021_Estimates.log',
          '#output/derived/Finkelstein_Gentzkow_Williams_2021_Replicates.log']
source = ['#source/derived/Finkelstein_Gentzkow_Williams_2021/clean_replicates.py',
          '#datastore/raw/Finkelstein_Gentzkow_Williams_2021/orig/FGW_AER2021_Table4_bootstraps.dta',
          '#source/derived/digits_after_comma_precision.txt',
          '#source/raw/orig/objects_of_interest.csv']
env.Python(target, source)
