Import('*')

target = ['#output/derived/Bourreau_Sun_Verboven_2021_Replicates.csv',
          '#output/derived/Bourreau_Sun_Verboven_2021_Estimates.csv',
          '#output/derived/Bourreau_Sun_Verboven_2021_Replicates.log',
          '#output/derived/Bourreau_Sun_Verboven_2021_Estimates.log']
source = ['#source/derived/Bourreau_Sun_Verboven_2021/clean_replicates.py',
          '#datastore/raw/Bourreau_Sun_Verboven_2021/data/bootstraps_table7.csv',
          '#datastore/raw/Bourreau_Sun_Verboven_2021/data/bootstraps_table8.csv',
          '#datastore/raw/Bourreau_Sun_Verboven_2021/data/bootstraps_table9.csv',
          '#source/raw/orig/objects_of_interest.csv']
env.Python(target, source)
