Import('*')

target = ['#output/derived/bootstrap_census/Goodman-Bacon_2021_Replicates.csv',
          '#output/derived/bootstrap_census/Goodman-Bacon_2021_Estimates.csv',
          '#output/derived/bootstrap_census/Goodman-Bacon_2021_Estimates.log',
          '#output/derived/bootstrap_census/Goodman-Bacon_2021_Replicates.log']
source = ['#source/derived/bootstrap_census/Goodman-Bacon_2021/clean_replicates.py',
          '#datastore/raw/bootstrap_census/Goodman-Bacon_2021/orig/table9.dta',
          '#source/derived/bootstrap_census/digits_after_comma_precision.txt',
          '#source/raw/bootstrap_census/orig/objects_of_interest.csv']
env.Python(target, source)
