Import('*')
import pandas as pd
import numpy as np
import sys
import os

df_papers = pd.read_csv('../../../source/raw/bootstrap_census/orig/papers.csv')
papers = df_papers.loc[np.invert((df_papers['date_received'] != 'X').values ^ (df_papers['date_received'] != 'N').values), 'citation'].values

for paper in papers:
    SConscript(f'{paper}/SConscript')
