Import('*')
import pandas as pd
import numpy as np

df_papers = pd.read_csv('../../source/raw/orig/papers.csv')
papers = df_papers.loc[np.invert((df_papers['date_received'] != 'X').values ^ (
    df_papers['date_received'] != 'N').values), 'citation'].values

for paper in papers:
    SConscript(f'{paper}/SConscript')

target = ['#output/derived/mismatched_replicates.csv']
source = ['#source/derived/replicate_integrity_check.py']
env.Python(target, source)
